export const HANDWRITTEN_PRICE_DATE = '1337-10-10T10:10:00';
 
export const MARKET_ORDER_FEE = 4;
export const MARKET_SETUP_FEE = 2.5;
export const MARKET_SELL_ORDER_FEE = MARKET_ORDER_FEE + MARKET_SETUP_FEE;